<?php

namespace WTF\CartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemRepository extends EntityRepository
{
}
